apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
  namespace: taskmanager
  labels:
    app: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for db; sleep 2; done;']
      containers:
        - name: taskmanager
          image: edkoto/taskmanager-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/taskmanager"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"

            - name: SPRING_FLYWAY_ENABLED
              value: "false"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"