apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
  namespace: taskmanager
  labels:
    app: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for db; sleep 2; done;']
      containers:
        - name: taskmanager
          image: edoto03/taskmanager-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-config
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskmanager-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO
            - name: SPRING_FLYWAY_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-config
                  key: SPRING_FLYWAY_ENABLED
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-config
                  key: SPRING_FLYWAY_BASELINE_ON_MIGRATE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: taskmanager-config
                  key: SERVER_PORT
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"