apiVersion: v1
kind: Service
metadata:
  name: postgres-service  # Must match the initContainer and ConfigMap
  namespace: taskmanager
spec:
  selector:
    app: postgres # Must match the label in your Postgres Deployment
  ports:
    - port: 5432
      targetPort: 5432