apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secret
  namespace: taskmanager
type: Opaque
stringData:
  # Database Credentials
  SPRING_DATASOURCE_USERNAME: "taskmanager"
  SPRING_DATASOURCE_PASSWORD: "taskmanager123"

  # PostgreSQL Admin Credentials
  POSTGRES_USER: "taskmanager"
  POSTGRES_PASSWORD: "taskmanager123"
  POSTGRES_DB: "taskmanager"