apiVersion: v1
kind: Secret
metadata:
  name: taskmanager-secret  # Matches your deployment
  namespace: taskmanager
type: Opaque
stringData:
  # These keys match the "secretKeyRef" in your deployment
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "password"